//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accepter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accepter()
        {
            this.comments = new HashSet<comment>();
            this.docuploads = new HashSet<docupload>();
            this.donations = new HashSet<donation>();
            this.posts = new HashSet<post>();
        }
    
        public int accepter_id { get; set; }
        public string accepter_name { get; set; }
        public string father_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string contact_no { get; set; }
        public string CNIC { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string address { get; set; }
        public string zip_code { get; set; }
        public string gender { get; set; }
        public string occupation { get; set; }
        public Nullable<int> family_members { get; set; }
        public string marital_status { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> code { get; set; }
        public string status { get; set; }
        public Nullable<int> admin_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<docupload> docuploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donation> donations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post> posts { get; set; }
    }
}
