//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> contact_no { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNIC { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string address { get; set; }
        public Nullable<int> code { get; set; }
        public string status { get; set; }
    }
}
