//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class docupload
    {
        public int doc_id { get; set; }
        public Nullable<int> accepter_id { get; set; }
        public Nullable<int> donor_id { get; set; }
        public string doc_name { get; set; }
        public string path { get; set; }
    
        public virtual accepter accepter { get; set; }
        public virtual donor donor { get; set; }
    }
}
