//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class steptocharityEntities : DbContext
    {
        public steptocharityEntities()
            : base("name=steptocharityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accepter> accepters { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<docupload> docuploads { get; set; }
        public virtual DbSet<donation> donations { get; set; }
        public virtual DbSet<donor> donors { get; set; }
        public virtual DbSet<imageupload> imageuploads { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<post> posts { get; set; }
    }
}
