//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post()
        {
            this.comments = new HashSet<comment>();
            this.donations = new HashSet<donation>();
            this.imageuploads = new HashSet<imageupload>();
        }
    
        public int post_id { get; set; }
        public string title { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public Nullable<int> target_amount { get; set; }
        public Nullable<int> received_amount { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> shares { get; set; }
        public string urgent { get; set; }
        public Nullable<int> accepter_id { get; set; }
        public Nullable<int> donor_id { get; set; }
    
        public virtual accepter accepter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donation> donations { get; set; }
        public virtual donor donor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imageupload> imageuploads { get; set; }
    }
}
